# Generated by Django 3.2.3 on 2021-05-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20210520_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='coverageRef',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='selected',
        ),
        migrations.AddField(
            model_name='coverage',
            name='description',
            field=models.TextField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coverage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CoverageRef',
        ),
    ]
