# Generated by Django 3.2.3 on 2021-05-20 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=12)),
                ('email', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculeYearMake', models.PositiveSmallIntegerField()),
                ('vehiculeModel', models.TextField(max_length=80)),
                ('vehiculePrice', models.DecimalField(decimal_places=2, default=100000, max_digits=10, validators=[django.core.validators.MinValueValidator(30000)])),
                ('quotationPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverageRef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quotations.coverageref')),
                ('quotation', models.ManyToManyField(to='quotations.Quotation')),
            ],
        ),
    ]
