# Generated by Django 3.2.3 on 2021-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_coverageref_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='coverage',
            field=models.ManyToManyField(to='quotations.Coverage'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotationPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
