# Generated by Django 3.2.3 on 2021-05-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20210520_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='coverage',
            new_name='coverages',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotations', to='quotations.customer'),
        ),
    ]
