# Generated by Django 3.2.3 on 2021-05-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_auto_20210520_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vehiculeNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='vehiculeModel',
            field=models.CharField(max_length=80),
        ),
    ]
