# Generated by Django 3.2.3 on 2021-05-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_auto_20210522_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vehiculeYearMake',
            field=models.PositiveSmallIntegerField(default=2021),
        ),
    ]
